# version: '3' # no es necesario especificarla

services:
  db:
    container_name: postgres_database
    image: postgres:16.1
    volumes:
      ### Volumen creado por docker compose en ruta asigando por docker
      # - postgres-db:/var/lib/postgresql/data
      ### Volumen bind de la carpeta actual del proyecto a la ruta del contenedor
      - ./postgres-db:/var/lib/postgresql/data # hay que comentario en volumnes externos para que funcione el bind
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432" # si voy a usar pgadmin del contenedor lo puedo quitar, lo pongo porque uso la aplicaci√≥n de escritorio

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456 
      - PGADMIN_DEFAULT_EMAIL=superman@google.com 
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin # volumen bind para manejo de datos de pgadmin

# volumes:
#   postgres-db:
#     external: true # si no se coloca crea el volumen usando el formato "<project-name>_<service-name>_<replica-number>" (<carpeta>_<nombre_del_servicio>_<numero_de_replica>)